TEST:
  BATCH_SIZE: 64

OPTIM:
  METHOD: Adam
  STEPS: 1
  BETA: 0.9
  LR: 1e-3
  WD: 0.

INPUT:
  SIZE: (32, 32)

ADAPTER:
  NAME: petta

  RoTTA:
    MEMORY_SIZE: 64
    UPDATE_FREQUENCY: 64
    
  PETTA:
    ALPHA_0: 0.001
    LAMBDA_0: 10.0
    REGULARIZER: "cosine"
    ADAPTIVE_LAMBDA: True
    ADAPTIVE_ALPHA: True
    NORM_LAYER: "rbn"
    
LOADER:
  SAMPLER:
    TYPE: "class_temporal"
    GAMMA: 0.01


    